apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-result-app
spec:
 containers:
 - name: result-app
   iamge: docker/example-voting-app-result
   ports:
   - containerPort: 80
   