apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: demo-voting-app
spec:
replicas: 1
selector:
 matchLabels:
    name: result-app-pod
    app: demo-result-app
template:
  
   
 

