apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-worker-app
spec:
 containers:
 - name: worker-app
   iamge: docker/example-voting-app-worker
   